### ISSUE TITLE
Error at downloading account name

### ISSUE THREAD

**Issue by lulinha93** [Procurement-PoE/Procurement#1068]
Error downloading account name.

DebugInfo log

[18-09-2019 17:19] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': The remote server returned an error: (503) Server Unavailable.
[18-09-2019 17:19] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/character-window/get-account-name?realm=pc', allowAutoRedirects=, requestData='': The remote server returned an error: (401) Unauthorized.
[18-09-2019 17:19] Error downloading account name, exception details: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.GetAccountName(String realm)
   at POEApi.Model.POEModel.GetAccountName(String realm)
[18-09-2019 17:19] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName(String realm)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[18-09-2019 17:19] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': The remote server returned an error: (503) Server Unavailable.
[18-09-2019 17:20] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/character-window/get-account-name?realm=pc', allowAutoRedirects=, requestData='': The remote server returned an error: (401) Unauthorized.
[18-09-2019 17:20] Error downloading account name, exception details: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.GetAccountName(String realm)
   at POEApi.Model.POEModel.GetAccountName(String realm)
[18-09-2019 17:20] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName(String realm)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()
[18-09-2019 17:20] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': The remote server returned an error: (503) Server Unavailable.
[18-09-2019 17:20] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/character-window/get-account-name?realm=pc', allowAutoRedirects=, requestData='': The remote server returned an error: (401) Unauthorized.
[18-09-2019 17:20] Error downloading account name, exception details: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.GetAccountName(String realm)
   at POEApi.Model.POEModel.GetAccountName(String realm)
[18-09-2019 17:20] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName(String realm)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by melink14** [comment]
Since you're getting a 401 unauthorized I wonder if you can double check that your poe session ID still matches what is shown at pathofexile.com when looking at application data using dev tools.

**Comment by eagl3s1ght** [comment]
> Since you're getting a 401 unauthorized I wonder if you can double check that your poe session ID still matches what is shown at pathofexile.com when looking at application data using dev tools.

Wait what?! Where was it ever mentioned that this is session-ID is required? 
Is the tool supposed to autofetch that ID or what's wrong here? 
Are we missing a good old instruction on how to use the tool perhaps?

**Comment by thailyn** [comment]
We can afford to improve our documentation, but you need to provide the Session ID to Procurement yourself.  The [typical method](https://github.com/Stickymaddness/Procurement/wiki/SessionID) is using the one obtained by logging in to the website.  GGG updated how their API worked several leagues ago, and Procurement has required logging in via Session ID since then, where using your GGG account name and password (for Procurement to get the Session ID for you) was removed from the app.
