### ISSUE TITLE
Procurement 1.26.0

### ISSUE THREAD

**Issue by slodzo** [Procurement-PoE/Procurement#987]
Debug.info

[11-03-2019 17:45] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': The remote server returned an error: (503) Server Unavailable.
[11-03-2019 17:45] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/character-window/get-account-name', allowAutoRedirects=, requestData='': The remote server returned an error: (401) Unauthorized.
[11-03-2019 17:45] Error downloading account name, exception details: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.GetAccountName()
   at POEApi.Model.POEModel.GetAccountName()
[11-03-2019 17:45] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName()
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass22_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by thailyn** [comment]
Hi, thanks for the report.  This is when trying to log in, correct?  It looks like Procurement failed to pass the CloudFlare authentication (503 and 401 errors).  Also if pathofexile.com is down, Procurement won't be able to log in, either.  Have you been able to log in before?  You can try logging out and back in on the website to get a new SessionId value, and use that in Procurement.

There are some known issues with the way we handle the CloudFlare authentication, and I'm looking into how to improve the process.

**Comment by slodzo** [comment]
It seems that i was on my profile page on pathofexile.com, but i wasnt loged in qq
Thank you for ur help. it works now!
